# Generated by Django 5.2 on 2025-04-13 10:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialKey',
            fields=[
                ('material_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='calculated_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='labor_time',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='miscellaneous_margin',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_margin',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit', models.CharField(choices=[('PC', 'per piece'), ('INCH', 'per inch')], default='PC', max_length=4)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('material_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialkey')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.accessory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(through='inventory.Product_Accessory', to='inventory.accessory'),
        ),
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit', models.CharField(choices=[('FT', 'per sq/ft'), ('INCH', 'per sq/inch'), ('M', 'per sq/m')], default='FT', max_length=4)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('material_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialkey')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('buffer', models.DecimalField(decimal_places=2, max_digits=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('textile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.textile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='textiles',
            field=models.ManyToManyField(through='inventory.Product_Component', to='inventory.textile'),
        ),
    ]
