# Generated by Django 5.2 on 2025-04-18 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_component',
            name='component',
        ),
        migrations.RemoveField(
            model_name='product_accessory',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='product_accessory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_component',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_component',
            name='textile',
        ),
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory', to='inventory.accessory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(through='inventory.ProductAccessory', to='inventory.accessory'),
        ),
        migrations.CreateModel(
            name='ProductTextile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.product')),
                ('textile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textile', to='inventory.textile')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='textiles',
            field=models.ManyToManyField(through='inventory.ProductTextile', to='inventory.textile'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Product_Accessory',
        ),
        migrations.DeleteModel(
            name='Product_Component',
        ),
    ]
