# Generated by Django 5.2 on 2025-04-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_component_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textile',
            name='material_key',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='material_key',
        ),
        migrations.DeleteModel(
            name='MaterialKey',
        ),
    ]
