# Generated by Django 5.2 on 2025-04-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productaccessory_quantity_producttextile_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaccessory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttextile',
            name='name',
        ),
    ]
