# Generated by Django 5.2 on 2025-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_productaccessory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccessory',
            name='name',
            field=models.CharField(default='slider', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttextile',
            name='name',
            field=models.CharField(default='carabao', max_length=255),
            preserve_default=False,
        ),
    ]
