# Generated by Django 5.2 on 2025-04-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_productaccessory_name_producttextile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaccessory',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='producttextile',
            old_name='quantity',
            new_name='stock',
        ),
    ]
