# Generated by Django 5.2 on 2025-04-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_quantity_productaccessory_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaccessory',
            name='name',
        ),
    ]
