# Generated by Django 5.2 on 2025-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_productaccessory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccessory',
            name='name',
            field=models.CharField(default='Slider', max_length=255),
            preserve_default=False,
        ),
    ]
