# Generated by Django 5.2 on 2025-04-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productaccessory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
