# Generated by Django 5.2 on 2025-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_calculated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=2345, max_digits=6),
            preserve_default=False,
        ),
    ]
