# Generated by Django 5.2 on 2025-04-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_product_calculated_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
    ]
