# Generated by Django 5.2 on 2025-04-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_product_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='textiles',
        ),
    ]
