# Generated by Django 5.2 on 2025-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_product_accessories_remove_product_textiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
