# Generated by Django 5.2 on 2025-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialKey',
            fields=[
                ('material_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
