# Generated by Django 5.2 on 2025-04-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_materialkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='material_key',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.materialkey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textile',
            name='material_key',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.materialkey'),
            preserve_default=False,
        ),
    ]
