# Generated by Django 5.2 on 2025-04-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_accessory_material_key_textile_material_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textile',
            name='material_key',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='material_key',
        ),
        migrations.DeleteModel(
            name='MaterialKey',
        ),
    ]
