# Generated by Django 5.2 on 2025-04-19 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_textile_material_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('outlet', models.CharField(choices=[('ES', 'Estancia'), ('CC', 'Commerce Center'), ('GH', 'Gray House'), ('OL', 'Online')])),
                ('status', models.CharField(choices=[('INQ', 'In-Queue'), ('COMP', 'Completed'), ('CANC', 'Cancelled'), ('INP', 'In-Progress')])),
                ('start_date', models.DateField()),
                ('file_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
