# Generated by Django 5.2 on 2025-04-19 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_order_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buffer',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaccessory',
            name='quantity',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttextile',
            name='height',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttextile',
            name='quantity',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttextile',
            name='width',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
